//go:build tools
// +build tools

package main

import (
	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/gambitier/gocomm/_apidocs"
	_ "github.com/golang-migrate/migrate/v4/cmd/migrate"
	_ "github.com/google/wire/cmd/wire"
	_ "github.com/sqlc-dev/sqlc/cmd/sqlc"
	_ "github.com/swaggo/swag/cmd/swag"
	_ "google.golang.org/grpc/cmd/protoc-gen-go-grpc"
	_ "google.golang.org/protobuf/cmd/protoc-gen-go"
)
